### ISSUE TITLE
App didn't work; I think this may be a scam

### ISSUE THREAD

**Issue by ak1878** [midnightchip/RelocateMe#4]
The app didn't seem to be compatible with my iphone 11 pro max 14.4.2. Not sure if I did something wrong or what could be causing it. The app opened up but wasn’t
able to press anything on the screen. Let me know if the issue can be determined by any chance (edited)

**Comment by midnightchip** [comment]
Hi, you sent me an email not more than 5 hours ago. I am a full time student and currently working on my final exams. I am sorry that I have not been able to refund you instantaneously, as I have to process the request. You did not include the purchase id in the email, or present any information regarding your device, jailbreak etc, making it extremely difficult to find the cause of your issue. Please *email* me your purchase id, do not post it here, and allow me time to process your refund.
